#!/usr/bin/env bash
# Configure my domain zone:
# www --> 39410-lb-01 18.209.179.35
# web-01 --> 39410-web-01 100.26.229.179
# web-02 --> 39410-web-02 54.146.82.165


subdomains_all=( "www" "lb-01" "web-01" "web-02" )

runDig () {
    subdomain="$1"
    domain="$2"

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
	    runDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    runDig "$subdomain" "$domain"
fi
