#!/usr/bin/env bash
# replacing 4 and 8 in the list

COUNTER=1

while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 4 ]
    then
        echo "bad luck"
    elif [ $COUNTER = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((COUNTER++))
done
