#!/usr/bin/env bash
# replaces 3 numbers in a 20 number loop

i=1
while [ $i -le 20 ]; do
	case $i in
	4)
		echo -e "$i\nbad luck from China"
		;;
	9)
		echo -e "$i\nbad luck from Japan"
		;;
	17)
		echo -e "$i\nbad luck from Italy"
		;;
	*)
		echo "$i"
		;;
	esac
	((i+=1))
done
